### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by yumengyang** [jenly1314/KingTV#10]
给你提个建议，可以把几大平台的全弄一起，用户可以根据自己的喜好选取各大平台喜欢的主播，下次用户就不用再切换软件那么麻烦，像我喜欢斗鱼的某位女主播，战旗的大哥，全民的小智，龙珠的miss，熊猫的PDD

**Comment by yumengyang** [comment]
1111

**Comment by buhanzhe** [comment]
你说的不是狗仔直播么

**Comment by jenly1314** [comment]
我写KingTV时的初衷是高仿，所以KingTV就是高仿全民TV，但你这个建议是不错，可能在有空余时间的时候，我会规划下，要不要重新开发一款整合版直播App。

**Comment by majiag** [comment]
@yumengyang miss 不是虎牙的？🙄？？
