### ISSUE TITLE
app/build.gradle error

### ISSUE THREAD

**Issue by flemingme** [jenly1314/KingTV#11]
Error:(17, 0) Neither path nor baseDir may be null or empty string. path='null' basedir='/home/fleming/AndroidStudioProjects/KingTV/app'
<a href="openFile:/home/fleming/AndroidStudioProjects/KingTV/app/build.gradle">Open File</a>

**Comment by ananas-xxj** [comment]
@flemingme 这错是怎么回事 @jenly1314
