### ISSUE TITLE
编译不过，大佬在吗

### ISSUE THREAD

**Issue by ananas-xxj** [jenly1314/KingTV#14]
Error:Could not find com.tencent.tinker:tinker-patch-gradle-plugin:1.7.11.
Searched in the following locations:
    file:/D:/Program Files/Android/Android Studio/gradle/m2repository/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.pom
    file:/D:/Program Files/Android/Android Studio/gradle/m2repository/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.jar
    https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.pom
    https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.jar
Required by:
    project : > com.tencent.bugly:tinker-support:1.0.8

**Comment by jenly1314** [comment]
这是你下载tinker失败了，最近几天tinker被jcenter下架了，只是暂时的，微信tinker开发人员正在解决，到时候就会好了。你如果现在想跑通，也可以注释掉tinker相关的代码。
