### ISSUE TITLE
导入时app下的build.gradle文件报错

### ISSUE THREAD

**Issue by hymbo** [jenly1314/KingTV#17]
//读取文件
   def storeFileDir = properties.getProperty('storeFile.file')
   storeFile file(storeFileDir) 这个方法报错，如下：

Error:(17, 0) Neither path nor baseDir may be null or empty string. path='null' basedir='F:\Rxjava_ReTrofit_okHttp\KingTV-master\app'
<a href="openFile:F:\KingTV-master\app\build.gradle">Open File</a>

**Comment by jenly1314** [comment]
[请戳](https://github.com/jenly1314/KingTV/issues/5)

**Comment by hymbo** [comment]
谢谢，前几天没看懂这位置代码的用处，我也是把它注释掉
