### ISSUE TITLE
编译出现了个错误Error:(17, 0) Neither path nor baseDir may be null or empty string. path='null' basedir='E:\myStudy\KingTV-master\app' <a href="openFile:E:\myStudy\KingTV-master\app\build.gradle">Open File</a>

### ISSUE THREAD

**Issue by tyx627** [jenly1314/KingTV#18]
Error:(17, 0) Neither path nor baseDir may be null or empty string. path='null' basedir='E:\myStudy\KingTV-master\app' <a href="openFile:E:\myStudy\KingTV-master\app\build.gradle">Open File</a>

build.gradle里面的

//读取文件
            def storeFileDir = properties.getProperty('storeFile.file')
            storeFile file( storeFileDir )
这里报错，要怎么解决？

**Comment by jenly1314** [comment]
[请戳](https://github.com/jenly1314/KingTV/issues/5)
