### ISSUE TITLE
有一个问题就是为什么看的都是别人的直播，自己却不能直播

### ISSUE THREAD

**Issue by huoyabingqian** [jenly1314/KingTV#2]
我的这个问题，在你的项目当中只能通过别观看别人的直播，为什么不能让自己也直播呀，我没找到在哪能让自己直播的功能

**Comment by jenly1314** [comment]
暂时未实现直播功能。

**Comment by ngochuu90** [comment]
@jenly1314 Can you suggest me to use the SDK to live stream
