### ISSUE TITLE
你好 ，导入出现这种错误，怎么修改呢

### ISSUE THREAD

**Issue by kirangao** [jenly1314/KingTV#5]
Error:(17, 0) Neither path nor baseDir may be null or empty string. path='null' basedir='C:\Users\Administrator\Desktop\123\KingTV-master\KingTV-master\app'
<a href="openFile:C:\Users\Administrator\Desktop\123\KingTV-master\KingTV-master\app\build.gradle">Open File</a>

**Comment by zhouxin1233** [comment]
我也出现了这种错误

**Comment by zhouxin1233** [comment]
我也提交了这个问题 ,  但没一会就被关了 ,唉

**Comment by CGL-A** [comment]
local.properties 没有对应字段值

**Comment by jenly1314** [comment]
我打包签名用的，直接运行肯定没有的，请注释掉build.gradle内签名相关的配置。示例如下
//    signingConfigs {
//        config {
//
//            //加载资源
//            Properties properties = new Properties()
//            InputStream inputStream = project.rootProject.file('local.properties').newDataInputStream() ;
//            properties.load( inputStream )
//
//            //读取文件
//            def storeFileDir = properties.getProperty('storeFile.file')
//            storeFile file( storeFileDir )
//
//            //读取字段
//            def key_keyAlias = properties.getProperty( 'keyAlias' )
//            def key_keyPassword = properties.getProperty( 'keyPassword' ) ;
//            def key_storePassword = properties.getProperty( 'storePassword' ) ;
//
//            keyAlias key_keyAlias
//            keyPassword key_keyPassword
//            storePassword key_storePassword
//        }
//    }


    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            signingConfig signingConfigs.config
        }
    }

**Comment by hymbo** [comment]
只是打包用的吗？我没看懂做什么用的，所以只能是注释掉它
