### ISSUE TITLE
same issue 

### ISSUE THREAD

**Issue by Lemonqsj** [jenly1314/KingTV#7]
Error:(17, 0) Cannot invoke method file() on null object
<a href="openFile:D:\code\pac\KingTV-master\KingTV-master\app\build.gradle">Open File</a>

    //读取文件
            def storeFileDir = properties.getProperty('storeFile.file')
            storeFile file( storeFileDir )

this part has some trombs,please deal with them

**Comment by jenly1314** [comment]
我打包签名用的，你注释掉签名相关配置就好了。
